env:
  browser: true
  es2021: true
extends:
  - 'airbnb'
  - 'airbnb/hooks'
parserOptions:
  ecmaVersion: 12
  sourceType: module
plugins:
  - react
rules:
  {
    linebreak-style: 'off',
    no-console: 'warn',
    react/jsx-filename-extension: [1, { 'extensions': ['.js', '.jsx'] }],
    no-plusplus: 'off',
    eol-last: 'off',
    max-len: ['error', 150, { ignoreUrls: true }],
    no-use-before-define: 'off',
    arrow-body-style: 'off',
    object-curly-newline: 'off',
    react/jsx-closing-bracket-location: 'off',
    import/no-unresolved: 'off',
    react/jsx-props-no-spreading: 'off',
    operator-linebreak: 'off',
    react/jsx-one-expression-per-line: 'off',
  }
