export const SET_CUSTOMERS_LIST_DATA = 'SET_CUSTOMERS_LIST_DATA';
export const SET_CURENT_CUSTOMER_INFO = 'SET_CURENT_CUSTOMER_INFO';
export const SET_AUTH_FLAG = 'SET_AUTH_FLAG';
export const SET_CUSTOMERS_LIST_CALC = 'SET_CUSTOMERS_LIST_CALC';
export const SET_CALCULATION_ID = 'SET_CALCULATION_ID';
export const SET_MATERIALS = 'SET_MATERIALS';
export const SET_USER_INFO = 'SET_USER_INFO';
export const CLEAR_USER_INFO = 'CLEAR_USER_INFO';
